apiVersion: v1
kind: Secret
metadata:
  name: prometheus-secret
  namespace: monitoring
type: Opaque
data:
  grafana-admin-password: cHJvbS1vcGVyYXRvcg==        # "myuser" en base64
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==  # "mypassword" en base64
  POSTGRES_DB: c3RyZWV0  # "mydatabase" en base64
  JWT_SECRET: bXlzZWNyZXRrZXk=
