apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: jimmymro/street-workout-partner-back:latest
        env:
        - name: DB_USER
          value: "postgres" 
        - name: DB_PASSWORD
          value: "mypassword"
        - name: DB_HOST
          value: "localhost"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "street"
        - name: JWT_SECRET
          value: "mysecretkey"
        ports:
        - containerPort: 5000  
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000  
      targetPort: 5000 
      nodePort: 30001
  type: NodePort  