apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=        # "myuser" en base64
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==  # "mypassword" en base64
  POSTGRES_DB: c3RyZWV0  # "mydatabase" en base64
  JWT_SECRET: bXlzZWNyZXRrZXk=
